#!/bin/sh

###
#
# Get the admin token for your kubernetes-dashboard.
#
###

set -e

SECRET_NAME=$(kubectl --namespace kubernetes-dashboard get secrets | grep admin-user | awk '{print $1}')
BASE64_SECRET=$(kubectl --namespace kubernetes-dashboard get secret $SECRET_NAME --template='{{ .data.token }}')
SECRET=$(echo "$BASE64_SECRET" | base64 --decode)

echo "$SECRET"
